{
    "config": {
        "error": {
            "cannot_connect": "Sikertelen csatlakoz\u00e1s",
            "invalid_auth": "\u00c9rv\u00e9nytelen hiteles\u00edt\u00e9s",
            "unknown": "V\u00e1ratlan hiba"
        },
        "step": {
            "user": {
                "data": {
                    "host": "Hoszt",
                    "password": "Jelsz\u00f3",
                    "port": "Port",
                    "ssl": "SSL tan\u00fas\u00edtv\u00e1nyt haszn\u00e1l",
                    "username": "Felhaszn\u00e1l\u00f3n\u00e9v",
                    "verify_ssl": "SSL-tan\u00fas\u00edtv\u00e1ny ellen\u0151rz\u00e9se"
                },
                "data_description": {
                    "host": "A QNAP eszk\u00f6z g\u00e9pneve vagy IP-c\u00edme."
                },
                "description": "Ez a qnap \u00e9rz\u00e9kel\u0151 lehet\u0151v\u00e9 teszi a k\u00fcl\u00f6nb\u00f6z\u0151 statisztik\u00e1k lek\u00e9r\u00e9s\u00e9t a QNAP NAS-r\u00f3l.",
                "title": "Csatlakozzon a QNAP eszk\u00f6zh\u00f6z"
            }
        }
    },
    "issues": {
        "deprecated_yaml": {
            "description": "A QNAP YAML konfigur\u00e1ci\u00f3j\u00e1nak be\u00e1ll\u00edt\u00e1sa elt\u00e1vol\u00edt\u00e1sra ker\u00fcl.\n\nA megl\u00e9v\u0151 YAML konfigur\u00e1ci\u00f3j\u00e1t automatikusan import\u00e1ltuk a felhaszn\u00e1l\u00f3i fel\u00fcletre.\n\nT\u00e1vol\u00edtsa el a QNAP YAML konfigur\u00e1ci\u00f3t a configuration.yaml f\u00e1jlb\u00f3l \u00e9s ind\u00edtsa \u00fajra a Home Assistantot, hogy megoldja ezt a probl\u00e9m\u00e1t.",
            "title": "A QNAP YAML konfigur\u00e1ci\u00f3 elt\u00e1vol\u00edt\u00e1sra ker\u00fcl"
        }
    }
}